name: Release

on:
  push:
    tags: ["*"]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: frknorg

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Update apt package index
        run: sudo apt-get update

      - name: Build
        run: cargo build --release --no-default-features
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trial
          path: target/release/trial

  release:
    name: Release
    needs: [build-api]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Trial API artifact
        uses: actions/download-artifact@v4
        with:
          name: trial
          path: artifacts/trial

      - name: Prepare release files
        run: |
          mkdir -p release
          cp artifacts/api/trial release/trial-x86_64
          chmod +x release/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/trial-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
